### ISSUE TITLE
Game research

### ISSUE THREAD

**Issue by bargemb** [nguyensjsu/fa18-202-brainy-amigos#1]
- Finalize on Game

**Comment by sneha-thomas1** [comment]
### Avengers
This game is to help the Avengers in getting back the stones from Thanos and save the universe. The player can choose which avenger character they are going to help. At each level of the game, they will have to get back one of the stones, which will add to their power, ie,

- Time stone can add extra time to their game.
- Mind stone can help them to control the enemies mind like make them freeze.
- Power Stone can give them additional power or weapons.
- Soul Sone can add extra life and so on.

**Comment by nikitabairagi** [comment]
**Brain it on!**

[https://play.google.com/store/apps/details?id=com.orbital.brainiton&hl=en_USis 
](url)
In above game user is drawing the object to complete the objective.

So instead of drawing we can use projectile idea from below game and ask the player to complete the objective. Basically here in place of walls we can create different shapes and ask user to complete the .
task. There can be multiple levels for different type of [task.]

[http://www.greenfoot.org/scenarios/21462#comment-51454
](url)

**Comment by AkshayPagar** [comment]
**Mystery Room Design Patterns**

The game will provide different rooms scenes. The objects in the room will have clues for identifying design patterns. The game is to identify different one or more design pattern associated with objects in the room. After clicking on particular object, the object will react as per some design pattern[i.e. clue].  

We will be setting the level of difficulty for users to play: Easy, Medium , Difficult. 

For E.g.: 
1. Suppose in a room, there is a remote controller and after clicking the remote controller, the lights are turning on and off. [Medium Difficulty]
Answer: Command Pattern

2. Suppose in a room, there is a phone charger and a universal adapter. After clicking on both the objects, the phone will start to charge. [Easy Difficulty] 
Answer:  Adapter Pattern

**Comment by bargemb** [comment]
Proceeding with Akshay's idea.

Mystery Room Design Patterns
